management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers

logging:
  level:
    org.springframework.web: INFO


court-case-service:
  base-url: https://court-case-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk
  jitter-factor: 0.5d

offender-search:
  base-url: https://probation-offender-search-dev.hmpps.service.justice.gov.uk

person-record-service:
  base-url: https://hmpps-person-record-dev.hmpps.service.justice.gov.uk

nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk

person-match-score:
  base-url: https://hmpps-person-match-score-dev.hmpps.service.justice.gov.uk

feature:
  flags:
    pass-hearing-id-to-court-case-service: true
    use-list-no-to-fetch-libra-case: true
    save_person_id_to_court_case_service: false
