management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      show-details: always
      path-mapping: "health"
      probes:
        enabled: true
server:
  port: 8180

court-case-service:
  base-url: http://localhost:8082/

offender-search:
  base-url: https://probation-offender-search-dev.hmpps.service.justice.gov.uk

person-match-score:
  base-url: https://hmpps-person-match-score-dev.hmpps.service.justice.gov.uk

nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk

person-record-service:
  base-url: http://localhost:8083/

hmpps.sqs:
  enabled: true
  provider: localstack
  region: eu-west-2
  queues:
    courtcasesqueue:
      queueUrl: http://localhost:4566/000000000000/court_cases_queue.fifo
      queueName: court_cases_queue.fifo
      subscribeTopicId: courtcasestopic
  topics:
    courtcasestopic:
      arn: "arn:aws:sns:eu-west-2:000000000000:court-cases-topic.fifo"

feature:
  flags:
    use-list-no-to-fetch-libra-case: true
    cpr_matcher: true

crime-portal-gateway-s3-bucket: "cpg-s3-bucket-name"

aws:
  endpoint-url: "http://localhost:4566"
  s3:
    bucket-name: cpg-s3-bucket
    large-hearings:
      bucket-name: cp-large-s3-bucket