GATEWAY_JMS_HOST: crime-portal-mirror-gateway-jms.crime-portal-mirror-gateway-prod

offender-search:
  base-url: https://probation-offender-search.hmpps.service.justice.gov.uk

court-case-service:
  base-url: https://court-case-service.apps.live-1.cloud-platform.service.justice.gov.uk

nomis-oauth:
  base-url: https://sign-in.hmpps.service.justice.gov.uk
