GATEWAY_JMS_HOST: crime-portal-mirror-gateway-jms.crime-portal-mirror-gateway-prod

offender-search:
  base-url: https://offender-search.probation.service.justice.gov.uk

court-case-service:
  base-url: https://court-case-service.apps.live-1.cloud-platform.service.justice.gov.uk

nomis-oauth:
  base-url: https://gateway.nomis-api.service.justice.gov.uk/
