management:
  security:
    enabled: false

cgi:
  jms:
    destination.name: CP_OutboundQueue

spring:
  artemis:
    mode: native
    host: ${jms.host:localhost}
    user: ${jms.username:jmsuser}
    password: ${jms.password:jmsuser}
    port: 5445

#  # Spring JMS Settings
#  jms:
#    listener:
#      acknowledge-mode: auto
#      auto-startup: false
#      concurrency: 5
#      max-concurrency: 10
#    pub-sub-domain: false

