management:
  security:
    enabled: false
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,env,loggers,configprops,metrics

logging:
  level:
    org.springframework.web: INFO
    org.apache.activemq: DEBUG
    org.springframework.jms: DEBUG

cgi:
  jms:
    destination.name: CP_OutboundQueue

spring:
  artemis:
    mode: native
    host: "crime-portal-mirror-gateway-jms.crime-portal-mirror-gateway-dev"
    user: ${GATEWAY_JMS_USERNAME}
    password: ${GATEWAY_JMS_PASSWORD}
    port: ${GATEWAY_JMS_PORT:5445}

court-case-service:
  base-url: https://court-case-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk

offender-search:
  base-url: https://offender-search.test.delius.probation.hmpps.dsd.io

nomis-oauth:
  base-url: https://gateway.t3.nomis-api.hmpps.dsd.io
