management:
  security:
    enabled: false

cgi:
  jms:
    destination.name: CP_OutboundQueue

spring:
  artemis:
    mode: native
    host: "localhost"
    user: "jmsuser"
    password: "jmsuser"
    port: 5445

court-case-service:
  base-url: http://localhost:8082/
