management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  endpoint:
    health:
      show-details: always
      path-mapping: "health"

server:
  port: 8180

court-case-service:
  base-url: http://localhost:8082/

offender-search:
  base-url: https://probation-offender-search-dev.hmpps.service.justice.gov.uk

nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk

# Localstack settings
aws:
  sqs-endpoint-url: "http://localhost:4566"
  region_name: eu-west-2
  access_key_id: foobar
  secret_access_key: foobar
  sns:
    court_case_matcher_endpoint_url: "http://localhost:4566"

messaging:
  sqs:
    enabled: true
