management:
  security:
    enabled: false
  health:
    probes:
      enabled: true
    jms:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      path-mapping: "health"

cgi:
  jms:
    destination.name: CP_OutboundQueue

spring:
  jms:
    cache:
      enabled: false
    listener:
      concurrency: 1
      max-concurrency: 1
  application:
    name: court-case-matcher
  security:
    oauth2:
      client:
        registration:
          offender-search-client:
            client-name: offender-search-client
            client-id: ${offender-search-client-id:offender-search-client}
            client-secret: ${offender-search-client-secret:clientsecret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            provider: nomis-oauth-service
          person-record-search-client:
            client-name: person-record-search-client
            client-id: ${person-record-search-client-id:person-record-search-client}
            client-secret: ${person-record-search-client-secret:clientsecret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            provider: nomis-oauth-service
        provider:
          nomis-oauth-service:
            token-uri: ${nomis-oauth.base-url:http://oauth:8095}/auth/oauth/token
      resourceserver:
        jwt:
          issuer-uri: ${nomis-oauth.issuer-base-url:${nomis-oauth.base-url}}/auth/issuer
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

court-case-service:
  case-put-url-template: /court/%s/case/%s
  case-by-hearing-id-url-template: /hearing/%s
  matches-by-case-defendant-post-url-template: /defendant/%s/grouped-offender-matches
  post-max-retries: 3
  min-backoff-seconds: 5
  jitter-factor: 0.5d

offender-search:
  post-match-url: /match
  post-search-url: /search
  ping-path: /health/ping
  max-retries: 3
  min-backoff-seconds: 5
  ignore-titles: "MISS,MRS,MS,MASTER,MR,MX,DR"
  use-dob-with-pnc: false

person-match-score:
  post-match-url: /match
  max-retries: 0
  min-backoff-seconds: 5

person-record-service:
  person-search-url: /person/search
  create-person-url: /person


feature:
  flags:
    pass-hearing-id-to-court-case-service: false
    match-on-every-no-record-update: true
    save_person_id_to_court_case_service: false

nomis-oauth:
  ping-path: /auth/ping

web:
  client:
    connect-timeout-ms: 20000
    read-timeout-ms: 20000
    write-timeout-ms: 20000

# Libra feed has today's case list and another case list for this many days hence. e.g. 25th and 28th July
case-feed-future-date-offset: 3
ou-code-length: 5

aws:
  region-name: eu-west-2

health:
  default-ping-path: /ping

hmpps:
  sqs:
    queueAdminRole: COURT_CASE_MATCHER_QUEUE_ADMIN

replay404:
  dry-run: true