management:
  security:
    enabled: false

cgi:
  jms:
    destination.name: CP_OutboundQueue

spring:
  artemis:
    mode: native
    host: "localhost"
    user: "jmsuser"
    password: "jmsuser"
    port: 5445

court-case-service:
  base-url: https://court-case-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk

offender-search:
  base-url: https://offender-search.test.delius.probation.hmpps.dsd.io

nomis-oauth:
  base-url: https://gateway.t3.nomis-api.hmpps.dsd.io