management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  endpoint:
    health:
      show-details: always
      path-mapping: "health"
  health:
    jms:
      enabled: true

logging:
  level:
    org.apache.activemq: DEBUG
    org.springframework.jms: DEBUG
    uk.gov.justice.probation.courtcasematcher.messaging.MessageReceiver: TRACE

GATEWAY_JMS_HOST: localhost
GATEWAY_JMS_USERNAME: jmsuser
GATEWAY_JMS_PASSWORD: jmsuser

court-case-service:
  base-url: http://localhost:8082/

offender-search:
  base-url: https://probation-offender-search-dev.hmpps.service.justice.gov.uk

nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk

# Localstack settings
aws:
  sqs-endpoint-url: "http://localhost:4566"

messaging:
  activemq:
    enabled: false
  sqs:
    enabled: true
    queue-name: "crime-portal-gateway-queue"
