management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers

logging:
  level:
    org.apache.activemq: DEBUG
    org.springframework.jms: DEBUG
    uk.gov.justice.probation.courtcasematcher.messaging.MessageReceiver: TRACE

GATEWAY_JMS_HOST: localhost
GATEWAY_JMS_USERNAME: jmsuser
GATEWAY_JMS_PASSWORD: jmsuser

court-case-service:
  base-url: http://localhost:8082/

offender-search:
  base-url: https://offender-search.test.delius.probation.hmpps.dsd.io

nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk
