
logging:
  level:
    org.springframework.web: INFO
    org.apache.activemq: DEBUG
    org.springframework.jms: DEBUG
    uk.gov.justice.probation.courtcasematcher.messaging.MessageReceiver: TRACE

GATEWAY_JMS_HOST: crime-portal-mirror-gateway-jms.crime-portal-mirror-gateway-preprod

offender-search:
  base-url: https://offender-search.pre-prod.delius.probation.hmpps.dsd.io

court-case-service:
  base-url: https://court-case-service-preprod.apps.live-1.cloud-platform.service.justice.gov.uk

nomis-oauth:
  base-url: https://gateway.preprod.nomis-api.service.hmpps.dsd.io
