management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      show-details: always
      path-mapping: "health"
      probes:
        enabled: true
server:
  port: 8180

court-case-service:
  base-url: http://localhost:8082/

offender-search:
  base-url: https://probation-offender-search-dev.hmpps.service.justice.gov.uk

person-match-score:
  base-url: https://hmpps-person-match-score-dev.hmpps.service.justice.gov.uk

nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk

person-record-service:
  base-url: http://localhost:8083/

# Localstack settings
aws:
  sqs:
    court_case_matcher_endpoint_url: "http://localhost:4566"
    court_case_matcher_queue_name: "court-case-matcher-queue"
    court_case_matcher_dlq_endpoint_url: "court-case-matcher-dlq"
    court_case_matcher_dlq_access_key_id: foobar
    court_case_matcher_dlq_secret_access_key: foobar
    court_case_matcher_access_key_id: foobar
    court_case_matcher_secret_access_key: foobar
  sns:
    court_case_matcher_endpoint_url: "http://localhost:4566"


messaging:
  sqs:
    enabled: true

feature:
  flags:
    pass-hearing-id-to-court-case-service: true
    use-list-no-to-fetch-libra-case: true

crime-portal-gateway-s3-bucket: "cpg-s3-bucket-name"