management:
  security:
    enabled: false

cgi:
  jms:
    destination.name: CP_OutboundQueue

#spring.activemq.broker-url=tcp://localhost:5445?ssl-enabled=true
spring:
  artemis:
    mode: native
    host: "localhost"
    user: "jmsuser"
    password: "jmsuser"
    port: 5445
