offender-search:
  base-url: https://probation-offender-search.hmpps.service.justice.gov.uk

court-case-service:
  base-url: https://court-case-service.apps.live-1.cloud-platform.service.justice.gov.uk
  jitter-factor: 0.5d

nomis-oauth:
  base-url: https://sign-in.hmpps.service.justice.gov.uk

feature:
  flags:
    use-offender-search-for-probation-status: true
    pass-hearing-id-to-court-case-service: true
    use-list-no-to-fetch-libra-case: true
    match-on-every-no-record-update: false

