management:
  security:
    enabled: false
  endpoint:
  endpoints:
    web:
      exposure:
        include: health,info,beans,env,loggers,configprops,metrics

logging:
  level:
    org.apache.activemq: DEBUG
    org.springframework.jms: DEBUG

GATEWAY_JMS_HOST: localhost

court-case-service:
  base-url: http://localhost:8082/

offender-search:
  base-url: https://offender-search.test.delius.probation.hmpps.dsd.io

nomis-oauth:
  base-url: https://gateway.t3.nomis-api.hmpps.dsd.io
