management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers

logging:
  level:
    org.springframework.web: INFO
    org.apache.activemq: DEBUG
    org.springframework.jms: DEBUG
    uk.gov.justice.probation.courtcasematcher.messaging.MessageReceiver: TRACE

GATEWAY_JMS_HOST: crime-portal-mirror-gateway-jms.crime-portal-mirror-gateway-dev

court-case-service:
  base-url: https://court-case-service-dev.apps.live-1.cloud-platform.service.justice.gov.uk

offender-search:
  base-url: https://probation-offender-search-dev.hmpps.service.justice.gov.uk

nomis-oauth:
  base-url: https://sign-in-dev.hmpps.service.justice.gov.uk

messaging:
  activemq:
    queueName: "CP_OutboundQueue"
