
offender-search:
  base-url: https://probation-offender-search-preprod.hmpps.service.justice.gov.uk

court-case-service:
  base-url: https://court-case-service-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
  jitter-factor: 0.5d

nomis-oauth:
  base-url: https://sign-in-preprod.hmpps.service.justice.gov.uk

person-match-score:
  base-url: https://hmpps-person-match-score-preprod.hmpps.service.justice.gov.uk

person-record-service:
  base-url: https://hmpps-person-record-preprod.hmpps.service.justice.gov.uk


feature:
  flags:
    save_person_id_to_court_case_service: false
    cpr_matcher: false
