management:
  security:
    enabled: false
  health:
    probes:
      enabled: true
    jms:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      path-mapping: "health"

cgi:
  jms:
    destination.name: CP_OutboundQueue

spring:
  jms:
    cache:
      enabled: false
    listener:
      concurrency: 1
      max-concurrency: 1
  application:
    name: court-case-matcher
  artemis:
    mode: native
    host: ${GATEWAY_JMS_HOST:localhost}
    user: ${GATEWAY_JMS_USERNAME}
    password: ${GATEWAY_JMS_PASSWORD}
    port: ${GATEWAY_JMS_PORT:5445}
  security:
    oauth2:
      client:
        registration:
          offender-search-client:
            client-name: offender-search-client
            client-id: ${offender-search-client-id:offender-search-client}
            client-secret: ${offender-search-client-secret:clientsecret}
            client-authentication-method: basic
            authorization-grant-type: client_credentials
            provider: nomis-oauth-service
        provider:
          nomis-oauth-service:
            token-uri: ${nomis-oauth.base-url:http://oauth:8095}/auth/oauth/token

court-case-service:
  case-put-url-template: /court/%s/case/%s
  matches-post-url-template: /court/%s/case/%s/grouped-offender-matches
  purge-absent-put-url-template: /court/%s/cases/purgeAbsent
  probation-status-detail-get-url-template: /offender/%s/probation-status-detail
  post-max-retries: 3
  min-backoff-seconds: 5

offender-search:
  post-match-url: /match
  ping-path: /health/ping
  max-retries: 3
  min-backoff-seconds: 5
  ignore-titles: "MISS,MRS,MS,MASTER,MR,MX,DR"
  use-dob-with-pnc: false

nomis-oauth:
  ping-path: /auth/ping

web:
  client:
    connect-timeout-ms: 20000
    read-timeout-ms: 5000
    write-timeout-ms: 5000

# Libra feed has today's case list and another case list for this many days hence. e.g. 25th and 28th July
case-feed-future-date-offset: 3
ou-code-length: 5

aws:
  region-name: eu-west-2

messaging:
  activemq:
    queueName: "CP_OutboundQueue"

health:
  default-ping-path: /ping

