version: 2.1

parameters:
  alerts-slack-channel:
    type: string
    default: probation_in_court_alerts_dev
  releases-slack-channel:
    type: string
    default: probation_in_court_alerts_prod

orbs:
  hmpps: ministryofjustice/hmpps@10

jobs:
  build:
    executor:
        name: hmpps/localstack
        jdk_tag: "21.0"
        localstack_tag: "3.0"
        services: "s3,sqs,sns"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle

  test-integration:
    executor:
      name: hmpps/localstack
      jdk_tag: "21.0"
      localstack_tag: "3.0"
      services: "s3,sqs,sns"
    steps:
      - checkout
      - hmpps/install_aws_cli
      - hmpps/wait_till_ready
      - run:
          name: Set up queues
          command: bash src/test/resources/localstack/setup-aws.sh
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run:
          environment:
            AWS_PROVIDER: localstack
            SPRING_PROFILES_ACTIVE: test-msg
          command: ./gradlew integrationTest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

  pact-publish:
    executor:
      name: hmpps/localstack
      jdk_tag: "21.0"
      localstack_tag: "3.0"
      services: "s3,sqs,sns"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run: PACTCONSUMER_VERSION=$CIRCLE_SHA1 PACTCONSUMER_TAGS=$CIRCLE_BRANCH ./gradlew -Dpact.writer.overwrite=true pactTest pactPublish
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
          jdk_tag: "21.0"
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
            - veracode-credentials

  test-integration:
    jobs:
      - test-integration

  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint_dev
          env: dev
          chart_name: court-case-matcher
      - hmpps/build_docker:
          name: build_docker
          requires:
            - build
            - helm_lint_dev
          filters:
            branches:
              only:
                - main
      - pact-publish:
          context: [hmpps-common-vars]
          requires:
            - build
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          helm_additional_args: --values ./court-case-matcher/values-live.yaml
          context:
            - hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - build_docker
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          helm_additional_args: --values ./court-case-matcher/values-live.yaml
          context:
            - hmpps-common-vars
            - court-probation-live-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          helm_additional_args: --values ./court-case-matcher/values-live.yaml
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          slack_notification: true
          context:
            - hmpps-common-vars
            - court-probation-live-prod
          requires:
            - request-prod-approval
