version: 2.1

parameters:
  alerts-slack-channel:
    type: string
    default: probation_in_court_alerts_dev
  releases-slack-channel:
    type: string
    default: probation_in_court_alerts_prod

orbs:
  hmpps: ministryofjustice/hmpps@10

jobs:
  build:
    executor:
      name: hmpps/java
      tag: "21.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run: ./gradlew build
      - run:
          name: Record the Application Version
          command: |
            $JAVA_HOME/bin/jar xvf build/libs/court-case-matcher-*.jar META-INF/build-info.properties
            APP_VERSION=$(grep 'build.version=' META-INF/build-info.properties | awk -F= '{print $2}')
            rm META-INF/build-info.properties
            # make up a good version name
            SHORT_HASH=$(git rev-parse --short HEAD)
            TAG=${APP_VERSION}.${SHORT_HASH}
            if [[ "${CIRCLE_BRANCH}" == "main" ]]; then
              TAG=${APP_VERSION}
            fi
            echo $TAG > ./app_version.txt
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - build/libs
            - build.gradle
            - app_version.txt

  test-integration:
    executor:
      name: hmpps/localstack
      jdk_tag: "21.0"
      localstack_tag: "3.0"
      services: "s3,sqs,sns"
    steps:
      - checkout
      - hmpps/install_aws_cli
      - hmpps/wait_till_ready
      - run:
          name: Set up queues
          command: bash src/test/resources/localstack/setup-sqs.sh
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run:
          environment:
            AWS_PROVIDER: localstack
            SPRING_PROFILES_ACTIVE: test-msg
          command: ./gradlew integrationTest
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

  pact-publish:
    executor:
      name: hmpps/java
      tag: "21.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
            - gradle-
      - run: PACTCONSUMER_VERSION=$CIRCLE_SHA1 PACTCONSUMER_TAGS=$CIRCLE_BRANCH ./gradlew -Dpact.writer.overwrite=true pactTest pactPublish
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

  build_docker:
    executor:
      name: hmpps/default
      tag: 3.12.4
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build container and publish to docker hub
          command: |
            APP_VERSION=$(cat ./app_version.txt)
            docker build --rm=false . \
               --tag "hmpps/court-case-matcher:$APP_VERSION" \
               --label "maintainer=info@digital.justice.gov.uk" \
               --label "app.version=$APP_VERSION" \
               --label "build.version=$APP_VERSION" \
               --label "build.number=$CIRCLE_BUILD_NUM" \
               --label "build.url=$CIRCLE_BUILD_URL" \
               --label "build.gitref=$CIRCLE_SHA1"
            if [[ "${CIRCLE_BRANCH}" == "main" ]]; then
              # publish to docker hub as the tag
             docker login -u="${QUAYIO_USERNAME}" -p="${QUAYIO_PASSWORD}" quay.io
             docker tag hmpps/court-case-matcher:$APP_VERSION quay.io/hmpps/court-case-matcher:$APP_VERSION
             docker tag hmpps/court-case-matcher:$APP_VERSION quay.io/hmpps/court-case-matcher:latest
             docker push quay.io/hmpps/court-case-matcher:$APP_VERSION
             docker push quay.io/hmpps/court-case-matcher:latest
            fi

workflows:
  version: 2
  scheduled:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
          jdk_tag: "21.0"
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
            - veracode-credentials

  test-integration:
    jobs:
      - test-integration

  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - build_docker:
          requires:
            - build
      - pact-publish:
          context: [hmpps-common-vars]
          requires:
            - build
      - hmpps/helm_lint:
          name: helm_lint_dev
          env: dev
          chart_name: court-case-matcher
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          helm_additional_args: --values ./court-case-matcher/values-live.yaml
          context:
            - hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - build_docker
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          helm_additional_args: --values ./court-case-matcher/values-live.yaml
          context:
            - hmpps-common-vars
            - court-probation-live-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          helm_additional_args: --values ./court-case-matcher/values-live.yaml
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          slack_notification: true
          context:
            - hmpps-common-vars
            - court-probation-live-prod
          requires:
            - request-prod-approval
