# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minReplicaCount: 1
maxReplicaCount: 2

image:
  repository: quay.io/hmpps/court-case-matcher
  tag: latest
  pullPolicy: Always
  port: 8080

ingress:
  controller: court-probation-dev
  enabled: true
  enable_whitelist: true
  hosts:
    - host: court-case-matcher-dev.apps.live-1.cloud-platform.service.justice.gov.uk
  path: /

env:
  JAVA_OPTS: "-Xmx512m"

spring:
  profile: dev,instrumented


resources:
  cpu:
    limit: 5000m
    request: 250m
  memory:
    limit: 1200Mi
    request: 350Mi

generic-prometheus-alerts:
  targetApplication: court-case-matcher
  alertSeverity: slack-hmpps-user-preferences
  businessHoursOnly: true
  sqsNumberAlertQueueNames:
    - "probation-in-court-team-development-court-case-matcher-queue"
    - "probation-in-court-team-development-court-case-matcher-dead-letter-queue"
  sqsAlertsTotalMessagesThreshold: 1
