generic-service:
  ingress:
    hosts:
      - court-case-matcher.apps.live-1.cloud-platform.service.justice.gov.uk
    tlsSecretName: court-probation-cert-secret

  autoscaling:
    minReplicas: 2
    maxReplicas: 6

  env:
    SPRING_PROFILES_ACTIVE: "prod,instrumented"

generic-prometheus-alerts:
    alertSeverity: probation_in_court_alerts_prod
    sqsNumberAlertQueueNames:
      - probation-in-court-prod-court-cases.fifo
      - probation-in-court-prod-court-cases-dlq.fifo
    sqsOldestAlertQueueNames:
      - probation-in-court-prod-court-cases.fifo
      - probation-in-court-prod-court-cases-dlq.fifo
    sqsAlertsTotalMessagesThreshold: 1