generic-service:
  ingress:
    hosts:
      - court-case-matcher.apps.live-1.cloud-platform.service.justice.gov.uk
    tlsSecretName: court-case-matcher-cert

  autoscaling:
    minReplicas: 2
    maxReplicas: 6