generic-service:
  ingress:
    hosts:
      - court-case-matcher-dev.apps.live-1.cloud-platform.service.justice.gov.uk
    tlsSecretName: court-probation-dev-cert-secret

  autoscaling:
    minReplicas: 1
    maxReplicas: 2

  env:
    SPRING_PROFILES_ACTIVE: "dev,instrumented"

generic-prometheus-alerts:
  alertSeverity: probation_in_court_alerts_dev