# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minReplicaCount: 2
maxReplicaCount: 6

image:
  repository: quay.io/hmpps/court-case-matcher
  tag: latest
  pullPolicy: Always
  port: 8080

ingress:
  controller: court-probation-preprod
  enabled: true
  enable_whitelist: true
  hosts:
    - host: court-case-matcher-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
  path: /

env:
  JAVA_OPTS: "-Xmx512m"

spring:
  profile: preprod,instrumented


resources:
  cpu:
    limit: 1000m
    request: 100m
  memory:
    limit: 1000Mi
    request: 500Mi
