
generic-service:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
  env:
    SPRING_PROFILES_ACTIVE: preprod,instrumented

  ingress:
    host: court-case-matcher-preprod.apps.live-1.cloud-platform.service.justice.gov.uk

  resources:
    limits:
      cpu: 5000m
      memory: 1200Mi
    requests:
      cpu: 500m
      memory: 700Mi
