# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minReplicaCount: 2
maxReplicaCount: 6

image:
  repository: docker.io/mojdigitalstudio/court-case-matcher
  tag: latest
  pullPolicy: Always
  port: 8080

ingress:
  controller: nginx
  enabled: true
  enable_whitelist: true
  hosts:
    - host: court-case-matcher.apps.live-1.cloud-platform.service.justice.gov.uk
      cert_secret: court-case-matcher-cert
  path: /

env:
  JAVA_OPTS: "-Xmx512m"
  PROCESS_COURT_CASE_MATCHER_MESSAGES: false

spring:
  profile: prod,sqs-messaging,instrumented

whitelist:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  mojvpn: "81.134.202.29/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"

resources:
  cpu:
    limit: 1000m
    request: 100m
  memory:
    limit: 1000Mi
    request: 500Mi

