# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

minReplicaCount: 2
maxReplicaCount: 6

image:
  repository: quay.io/hmpps/court-case-matcher
  tag: latest
  pullPolicy: Always
  port: 8080

ingress:
  controller: nginx
  enabled: true
  enable_whitelist: true
  hosts:
    - host: court-case-matcher.apps.live-1.cloud-platform.service.justice.gov.uk
      cert_secret: court-case-matcher-cert
  path: /

env:
  JAVA_OPTS: "-Xmx1024m"

spring:
  profile: prod,instrumented


resources:
  cpu:
    limit: 1000m
    request: 100m
  memory:
    limit: 2Gi
    request: 1Gi

generic-prometheus-alerts:
  targetApplication: court-case-matcher
  alertSeverity: probation_in_court_alerts_prod
  sqsNumberAlertQueueNames:
    - "probation-in-court-prod-court-case-matcher-queue"
    - "probation-in-court-prod-court-case-matcher-dead-letter-queue"
  sqsAlertsTotalMessagesThreshold: 1