
generic-service:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
  env:
    SPRING_PROFILES_ACTIVE: dev,instrumented

  ingress:
    host: court-case-matcher-dev.apps.live-1.cloud-platform.service.justice.gov.uk

  resources:
    limits:
      cpu: 5000m
      memory: 1200Mi
    requests:
      cpu: 250m
      memory: 350Mi
