generic-service:
  ingress:
    # TODO: Should we have a custom tls cert for court-case-matcher?
    hosts:
      - court-case-matcher.apps.live-1.cloud-platform.service.justice.gov.uk

  autoscaling:
    minReplicas: 2
    maxReplicas: 6