generic-service:
  ingress:
    hosts:
      - court-case-matcher.apps.live-1.cloud-platform.service.justice.gov.uk
    tlsSecretName: court-probation-cert-secret

  autoscaling:
    minReplicas: 2
    maxReplicas: 6

  env:
    SPRING_PROFILES_ACTIVE: "prod,instrumented"